title: Boqiao (Steven) Zhang
logo: /assets/images/headshot_square.jpg
description: > 
  <br>
  MPhil in Machine Learning and Machine Intelligence (MLMI), Department of Engineering, University of Cambridge
show_downloads: false
theme: jekyll-theme-minimal
